include "root" {
  path = find_in_parent_folders("root.hcl")
  expose  = true
}

terraform {
  source = "../../../modules/cluster-dns"
}

dependency "env_cluster" {
 config_path = "../cluster"
 mock_outputs = {
    kube_host = "https://my-aks-cluster-12345678.hcp.uksouth.azmk8s.io:443"
    resource_group_name = "a-resource-group"
    fq_cluster_name = "aks-cluster-name"
    cluster_ca_certificate = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRakNDQWZnZ0F3SUJBZ0lVSWJvOXh1ekVXTzBBRWd5QjI0RUY4ZmFzSHdZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2N6RUxNQWtHQTFVRUJoTUNWVk14RHpBTkJna3Foa2lHOXcwQkNRRVdLQ1VnQ1FZRFZRUUdFd0pWVXpFRApNQWtHQTFVRUF3d0hhR1Z5WlhKaGRHOXlNQjRYRFRFNU1ETXdPREUxTXpJd05Gb1hEVEk1TURNeU5ERTFNekl3Ck5Gb3dVekVMTUFrR0ExVUVDaE1DVlZNeER6QU5CZ2txaGtpRzl3MEJDUUVXQmdVd0lGQWRCZ05WSFE0RUZnUVUKSm5BTm5oM1ZDUERvU3p5bDBFdzFkTkptWGkrV0F3SHdZRFZSMGpCQmd3Rm9BVUpuQU5uaDNWQ1BEb1N6eWwwRQp3MWROTm1YaStXQXdId1lEVlIwakJCZ3dGb0FVSm5BTm5oM1ZDUERvU3p5bDBFdzFkTkptWGkrV0F3SkJnWUEwCkJBUURBZ05JQURCRkFpQWZCZ05WSFNNRUdEQVdnQlVjbDBlWkRuNlFVa3hnSlRkM0Frd0NnWUlLb1pJemowRUEKQkFBT0JRS0FNSGlMZVFsMXFFcGpMRVBkQlAxZDNqYUpBaTRJSmpZUG5jU3JYbXRaQkNPM3V0R1B2aFB3K0dRQQp0czF3QjFTVkhSaXdiN3BNNEZWMFFqMUh3QXZnZGZ2N2ZHVlhZMHlDRnByVTFmUExRT2NoRXcvNWxyZXNQUUVECkFBd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFtNFVZMGxyZmFiY0lvZytCWjM4amV6blZTRUVZb1dPUVhTdGgKYU1NZ01Dd0dBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNR1V4R1RBWEJnTlZCQW9UQURCRU1Rc3dDUVlEVlFRRwpCUUJBUVVGQkFNTUNnWUlLb1pJemowRUF3SURTQUF3UlFJZ01ERUxNQWtHQTFVRUJ4TU1TV2x2YkdSbGNtbGgKWTJGc0xYTnZibXh2Y0d4bExtTnZiUzh4RURBT0JnTlZIUThCQWY4RUJBTUNCNEF3Z2dJaU1BMEdDU3FHU0liMwpDQ0FHUUFJaEFtNFVZMGxyZmFiY0lvZytCWjM4amV6blZTRUVZb1dPUVhTdGhhTU1nTTNFakFBTUJnTlZIUk1CCkFmOEVDREFPQmdOVkhSTUJBZjhFQ0RBT0JnTlZIUThCQWY4RUJBTUNCNEF3Z2dJaU1BMEdDU3FHU0liM0RRRUIKQlFJZ0ZCUUlEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUF2TmtaUnRLaXZrYTNXY0IvMFRMSmU2RXhnbjY3VApkUUhLU0d5bkU0UXdJaVRpdVFTS1daSDBKcW91aXQzSHZ4cnl0anQzS1E0b0M5Y0duRUJIQmxSSDRIZDNRUmIwCjVjU1MwYXR2WjJvUU9FV3VwZVd2VEFIdlZzVW9vR2RlcXl0OVNvVmtBM1hJWGZONXQvdkh6NGIzOEVqSldZK1UKb1lNVVdlSlZiUlFCNmE2a1hzZlJTSjBTK2dLMWNjcnVDbzJzUE9KQ1RtYkNmd25vUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    client_certificate = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRakNDQWZnZ0F3SUJBZ0lVSWJvOXh1ekVXTzBBRWd5QjI0RUY4ZmFzSHdZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2N6RUxNQWtHQTFVRUJoTUNWVk14RHpBTkJna3Foa2lHOXcwQkNRRVdLQ1VnQ1FZRFZRUUdFd0pWVXpFRApNQWtHQTFVRUF3d0hhR1Z5WlhKaGRHOXlNQjRYRFRFNU1ETXdPREUxTXpJd05Gb1hEVEk1TURNeU5ERTFNekl3Ck5Gb3dVekVMTUFrR0ExVUVDaE1DVlZNeER6QU5CZ2txaGtpRzl3MEJDUUVXQmdVd0lGQWRCZ05WSFE0RUZnUVUKSm5BTm5oM1ZDUERvU3p5bDBFdzFkTkptWGkrV0F3SHdZRFZSMGpCQmd3Rm9BVUpuQU5uaDNWQ1BEb1N6eWwwRQp3MWROTm1YaStXQXdId1lEVlIwakJCZ3dGb0FVSm5BTm5oM1ZDUERvU3p5bDBFdzFkTkptWGkrV0F3SkJnWUEwCkJBUURBZ05JQURCRkFpQWZCZ05WSFNNRUdEQVdnQlVjbDBlWkRuNlFVa3hnSlRkM0Frd0NnWUlLb1pJemowRUEKQkFBT0JRS0FNSGlMZVFsMXFFcGpMRVBkQlAxZDNqYUpBaTRJSmpZUG5jU3JYbXRaQkNPM3V0R1B2aFB3K0dRQQp0czF3QjFTVkhSaXdiN3BNNEZWMFFqMUh3QXZnZGZ2N2ZHVlhZMHlDRnByVTFmUExRT2NoRXcvNWxyZXNQUUVECkFBd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFtNFVZMGxyZmFiY0lvZytCWjM4amV6blZTRUVZb1dPUVhTdGgKYU1NZ01Dd0dBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNR1V4R1RBWEJnTlZCQW9UQURCRU1Rc3dDUVlEVlFRRwpCUUJBUVVGQkFNTUNnWUlLb1pJemowRUF3SURTQUF3UlFJZ01ERUxNQWtHQTFVRUJ4TU1TV2x2YkdSbGNtbGgKWTJGc0xYTnZibXh2Y0d4bExtTnZiUzh4RURBT0JnTlZIUThCQWY4RUJBTUNCNEF3Z2dJaU1BMEdDU3FHU0liMwpDQ0FHUUFJaEFtNFVZMGxyZmFiY0lvZytCWjM4amV6blZTRUVZb1dPUVhTdGhhTU1nTTNFakFBTUJnTlZIUk1CCkFmOEVDREFPQmdOVkhSTUJBZjhFQ0RBT0JnTlZIUThCQWY4RUJBTUNCNEF3Z2dJaU1BMEdDU3FHU0liM0RRRUIKQlFJZ0ZCUUlEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUF2TmtaUnRLaXZrYTNXY0IvMFRMSmU2RXhnbjY3VApkUUhLU0d5bkU0UXdJaVRpdVFTS1daSDBKcW91aXQzSHZ4cnl0anQzS1E0b0M5Y0duRUJIQmxSSDRIZDNRUmIwCjVjU1MwYXR2WjJvUU9FV3VwZVd2VEFIdlZzVW9vR2RlcXl0OVNvVmtBM1hJWGZONXQvdkh6NGIzOEVqSldZK1UKb1lNVVdlSlZiUlFCNmE2a1hzZlJTSjBTK2dLMWNjcnVDbzJzUE9KQ1RtYkNmd25vUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    client_key = "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQo="
    environment = "k8sman"
    oidc_issuer_url = "https://sts.windows.net/12345678-90ab-cdef-1234-567890abcdef/"
  }

  mock_outputs_allowed_terraform_commands = ["plan", "refresh"]
  mock_outputs_merge_strategy_with_state = "shallow"
}

inputs = {
  # region       = include.env_dev.locals.region
  # cluster_name  = include.env_dev.locals.cluster_name
  # cluster_tenant_id = include.root.locals.azure_tenant_id

  cluster_subscription_id = include.root.locals.azure_k8tre_mgmt_cluster_subscription_id
  azure_k8tre_connectivity_subscription_id = include.root.locals.azure_k8tre_connectivity_subscription_id

  kube_host = dependency.env_cluster.outputs.kube_host
  cluster_ca_certificate = dependency.env_cluster.outputs.cluster_ca_certificate
  cluster_resource_group_name = dependency.env_cluster.outputs.resource_group_name
  fq_cluster_name = dependency.env_cluster.outputs.fq_cluster_name

  cluster_name = dependency.env_cluster.outputs.environment
  cluster_domain_name = "mgmt.k8tre.internal"

  oidc_issuer_url = dependency.env_cluster.outputs.oidc_issuer_url
  azure_tenant_id = include.root.locals.azure_tenant_id
  spn_client_id = include.root.locals.spn_client_id

  lz_hub_vnet_name = include.root.locals.lz_hub_vnet_name
  lz_network_resource_group_name = include.root.locals.lz_network_resource_group_name 
  lz_network_dns_resource_group_name = include.root.locals.lz_network_dns_resource_group_name


}